sendmail/sendmail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

sendmail/website/urls.py
from django.urls import path
from . import views


app_name = 'website'


urlpatterns = [
    path('', views.home, name='home'),
    # path(views.home1, name='home1'),
    # path('', views.contact, name='contact'),
    path('send_gmail/', views.send_gmail, name='send_gmail'),
    # path('send_mail/', send_gmail, name="send_mail"),
]

sendmail/website/models.py
from django.db import models

# Create your models here.

sendmail/website/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


# # Create your views here.
#
#
# def home(request):
#     return HttpResponseRedirect(reverse('website:home'))


def home(request):
    return render(request, 'home.html', {})

# def contact(request):
#     if request.method == 'POST':
#         messageName = request.POST['messsageName']
#         messageEmail = request.POST['messsageEmail']
#         message = request.POST['messsage']
#         send_mail(
#             messageName,
#             message,
#             messageEmail,
#             ['a@a.a'] #receptionist(s)
#         )
#     return render(request, 'contact.html', {'messageName':messageName})
#
#
# def send_mail(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         subject = request.POST.get('subject')
#         text = request.POST.get('text')
#         print(name, subject, text)
#         return HttpResponseRedirect(reverse('home'))
#     else:
#         return HttpResponse('invalid request')


def send_gmail(request):
    # print('here')
    if request.method == "POST":
        # print('saggggggggggggggggggggggggggggggggggg')
        name = request.POST.get('name')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        # name = request.POST.post('name')
        # subject = request.POST.post('subject')
        # message = request.POST.post('message')
        print(name, subject, message)

        send_mail(
            subject,
            message,
            'sad.splitwise@gmail.com',
            ['dahlia.davoudi17@gmail.com'],
            fail_silently=False,
        )

        return HttpResponseRedirect(reverse('website:home'))
    else:
        return HttpResponse('Invalid request')

sendmail/website/templates/contact.html
<h1>CONTACT</h1>

sendmail/website/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAD-splitwise-sendMail</title>
</head>
<body>
    <h1>E-mail</h1>
    <form action="{% url 'website:send_gmail' %}" method="POST">
<!--    <form action="/send_mail/" method="POST">-->
        {% csrf_token %}
        <div>
            <label for="name">Name:</label>
            <input id="name" name="name" type="text" placeholder="Put Your name">
        </div>
        <div>
            <label for="sbj">Subject:</label>
            <input id="sbj" name="subject" type="text" placeholder="Put Your subject">
        </div>
        <div>
            <label for="msg">Message:</label>
            <input id="msg" name="message" type="text" placeholder="Put Your message">
        </div>
        <input type="submit", value="Send E-mail">

    </form>
</body>


<!--<a href="home.html">first bloody page</a>-->
</html>

sendmail/website/templates/home1.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<style>-->
<!--  @import "compass/css3";-->

<!--@import url(https://fonts.googleapis.com/css?family=Merriweather);-->
<!--$red: #e74c3c;-->

<!--*,-->
<!--*:before,-->
<!--*:after {-->
<!--   @include box-sizing(border-box);-->
<!--}-->

<!--html, body {-->
<!--  background: #c9ffeb;-->
<!--  font-family: 'Merriweather', sans-serif;-->
<!--  padding: 1em;-->
<!--}-->

<!--h1 {-->
<!--   text-align: center;-->
<!--   color: #a8a8a8;-->
<!--   @include text-shadow(1px 1px 0 rgba(white, 1));-->
<!--}-->

<!--&lt;!&ndash;.button1 {&ndash;&gt;-->
<!--&lt;!&ndash;  background-color: white;&ndash;&gt;-->
<!--&lt;!&ndash;  color: black;&ndash;&gt;-->
<!--&lt;!&ndash;  border: 2px solid #4CAF50;&ndash;&gt;-->
<!--&lt;!&ndash;}&ndash;&gt;-->

<!--&lt;!&ndash;.button1:hover {&ndash;&gt;-->
<!--&lt;!&ndash;  background-color: #4CAF50;&ndash;&gt;-->
<!--&lt;!&ndash;  color: white;&ndash;&gt;-->
<!--&lt;!&ndash;}&ndash;&gt;-->

<!--form {-->
<!--   max-width: 600px;-->
<!--   text-align: center;-->
<!--   margin: 20px auto;-->

<!--  input, textarea {-->
<!--     border:0; outline:0;-->
<!--     padding: 1em;-->
<!--     @include border-radius(8px);-->
<!--     display: block;-->
<!--     width: 100%;-->
<!--     margin-top: 1em;-->
<!--     font-family: 'Merriweather', sans-serif;-->
<!--     @include box-shadow(0 1px 1px rgba(black, 0.1));-->
<!--     resize: none;-->

<!--    &:focus {-->
<!--       @include box-shadow(0 0px 2px rgba($red, 1)!important);-->
<!--    }-->
<!--  }-->

<!--  #input-submit {-->
<!--     color: white;-->
<!--     background: $red;-->
<!--     cursor: pointer;-->

<!--    &:hover {-->
<!--       @include box-shadow(0 1px 1px 1px rgba(#aaa, 0.6));-->
<!--    }-->
<!--  }-->

<!--  textarea {-->
<!--      height: 126px;-->
<!--  }-->
<!--}-->


<!--.half {-->
<!--  float: left;-->
<!--  width: 48%;-->
<!--  margin-bottom: 1em;-->
<!--}-->

<!--.right { width: 50%; }-->

<!--.left {-->
<!--     margin-right: 2%;-->
<!--}-->


<!--@media (max-width: 480px) {-->
<!--  .half {-->
<!--     width: 100%;-->
<!--     float: none;-->
<!--     margin-bottom: 0;-->
<!--  }-->
<!--}-->


<!--/* Clearfix */-->
<!--.cf:before,-->
<!--.cf:after {-->
<!--    content: " "; /* 1 */-->
<!--    display: table; /* 2 */-->
<!--}-->

<!--.cf:after {-->
<!--    clear: both;-->
<!--}-->
<!--</style>-->

<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>Django Mail Demo</title>-->
<!--</head>-->

<!--<h1>Send E-mail</h1>-->


<!--<template>-->
<!--  <h2>Flower</h2>-->
<!--&lt;!&ndash;  <img src="img_white_flower.jpg" width="214" height="204">&ndash;&gt;-->
<!--</template>-->

<!--<script>-->
<!--function showContent() {-->
<!--  var temp = document.getElementsByTagName("template")[0];-->
<!--  var clon = temp.content.cloneNode(true);-->
<!--  document.body.appendChild(clon);-->
<!--}-->
<!--</script>-->


<!--&lt;!&ndash;<form action=""></form>&ndash;&gt;-->


<!--<form class="cf" action="{% url 'send_mail' %}" method="POST">-->
<!--  {% csrf_token %}-->
<!--  <div class="half left cf">-->
<!--    <input name="text" type="text" id="input-name" placeholder="Name">-->
<!--    <input name="email" type="email" id="input-email" placeholder="Email address">-->
<!--    <input name="subject" type="text" id="input-subject" placeholder="Subject">-->
<!--  </div>-->
<!--  <div class="half right cf">-->
<!--    <textarea name="message" type="text" id="input-message" placeholder="Message"></textarea>-->
<!--  </div>-->
<!--  <input type="submit" value="Submit" id="input-submit">-->
<!--&lt;!&ndash;  <button class="button button1">Submit</button>&ndash;&gt;-->

<!--</form>-->

<!--&lt;!&ndash;<button onclick="showContent()">SEND</button>&ndash;&gt;-->